// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vizehaber.Models;

#nullable disable

namespace vizehaber.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109125735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vizehaber.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Siyaset alanında uzman gazeteci.",
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2288),
                            Email = "ahmet@yazar.com",
                            IsActive = true,
                            Name = "Ahmet Yazar",
                            Password = "1234",
                            PhotoPath = "/userPhotos/ahmet.jpg",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2289)
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Ekonomi yazılarıyla tanınan deneyimli yazar.",
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2291),
                            Email = "ayse@yazar.com",
                            IsActive = true,
                            Name = "Ayşe Yazar",
                            Password = "1234",
                            PhotoPath = "/userPhotos/ayse.jpg",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2292)
                        });
                });

            modelBuilder.Entity("vizehaber.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2091),
                            IsActive = true,
                            Name = "Siyaset",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2102)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2105),
                            IsActive = true,
                            Name = "Ekonomi",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2105)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2112),
                            IsActive = true,
                            Name = "Spor",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2112)
                        });
                });

            modelBuilder.Entity("vizehaber.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("vizehaber.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Content = "Siyaset gündemine dair haber 1.",
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2332),
                            IsActive = true,
                            IsApproved = false,
                            PublishedDate = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2331),
                            Title = "Siyaset Haberi 1",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2333)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            Content = "Ekonomiyle ilgili haber 1.",
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2336),
                            IsActive = true,
                            IsApproved = false,
                            PublishedDate = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2335),
                            Title = "Ekonomi Haberi 1",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2336)
                        });
                });

            modelBuilder.Entity("vizehaber.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2308),
                            Email = "ali@user.com",
                            FullName = "Ali Kullanıcı",
                            IsActive = true,
                            Password = "1234",
                            PhotoPath = "/userPhotos/ali.png",
                            Role = "User",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2309),
                            UserName = "alikullanici"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2312),
                            Email = "admin@admin.com",
                            FullName = "Admin Kullanıcı",
                            IsActive = true,
                            Password = "admin",
                            PhotoPath = "/userPhotos/admin.png",
                            Role = "Admin",
                            Updated = new DateTime(2025, 11, 9, 15, 57, 35, 6, DateTimeKind.Local).AddTicks(2312),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("vizehaber.Models.News", b =>
                {
                    b.HasOne("vizehaber.Models.Author", "Author")
                        .WithMany("News")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vizehaber.Models.Category", "Category")
                        .WithMany("NewsList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("vizehaber.Models.Author", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("vizehaber.Models.Category", b =>
                {
                    b.Navigation("NewsList");
                });
#pragma warning restore 612, 618
        }
    }
}
